runtime: go
api_version: go1

handlers:
- url: /tasks/.*
  script: _go_app
  login: admin
- url: /invite
  script: _go_app
  login: admin
  secure: always
- url: /static/images
  static_dir: static/images
- url: /static/css
  static_dir: static/css
- url: /static/backgrounds
  static_dir: static/backgrounds
  application_readable: true
- url: /.*
  script: _go_app
  secure: always
